layout_spectrum: 0.8960574
color:
  saturation: 0.797491
  lightness: 0.469534
  brandStrength: 0.8261649
  brandColors:
    - '#EBEBEB'
    - '#272727'
    - '#D8BCAC'
    - '#646466'
    - '#BD9078'
  rhythmicContrast: 0.4498208
typography_spectrum: 0.4982079
name: Home Theater San Diego
